"""
Report Service - PDF and CSV Export
Generates professional deliverables for users.
"""

from typing import Dict, Any, Optional
from datetime import datetime
import io

try:
    # fpdf2 package is installed, but imported as 'fpdf'
    from fpdf import FPDF
except ImportError:
    # Fallback: Create a stub if fpdf2 is not installed
    class FPDF:
        """Stub FPDF class if fpdf2 is not installed"""
        def __init__(self):
            pass
        def add_page(self):
            pass
        def cell(self, *args, **kwargs):
            pass
        def ln(self, *args):
            pass
        def set_font(self, *args, **kwargs):
            pass
        def output(self, *args, **kwargs):
            return b'PDF generation requires fpdf2 package. Please install: pip install fpdf2'


class PDFReport(FPDF):
    """Custom PDF class for NexSupply reports"""
    
    def header(self):
        # Logo placeholder
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'NexSupply AI', 0, 1, 'L')
        self.set_font('Arial', '', 10)
        self.cell(0, 5, f'Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', 0, 1, 'L')
        self.ln(5)
    
    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Generated by NexSupply AI - Estimate Only', 0, 0, 'C')


def generate_pdf(analysis_result: Dict[str, Any], request_id: Optional[str] = None) -> bytes:
    """
    Generate a professional PDF report from analysis results.
    
    Args:
        analysis_result: Complete analysis result dictionary
        request_id: Optional request ID for tracking
        
    Returns:
        PDF file as bytes
    """
    pdf = PDFReport()
    pdf.add_page()
    
    # Title
    pdf.set_font('Arial', 'B', 18)
    pdf.cell(0, 10, 'Sourcing Analysis Report', 0, 1, 'C')
    pdf.ln(5)
    
    # Executive Summary
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, 'Executive Summary', 0, 1, 'L')
    pdf.set_font('Arial', '', 10)
    pdf.ln(3)
    
    # Verdict
    verdict_info = analysis_result.get('verdict', {})
    verdict_text = str(verdict_info.get('verdict', 'N/A'))
    pdf.set_font('Arial', 'B', 12)
    # Ensure text is properly encoded for PDF
    try:
        pdf.cell(0, 8, f'Verdict: {verdict_text}', 0, 1, 'L')
    except (UnicodeEncodeError, TypeError) as e:
        # If encoding fails, use ASCII fallback
        pdf.cell(0, 8, 'Verdict: N/A', 0, 1, 'L')
    
    # Key Metrics
    profitability = analysis_result.get('profitability', {})
    if profitability:
        unit_ddp = profitability.get('unit_ddp', 0)
        margin_percent = profitability.get('net_profit_percent', 0)
        pdf.set_font('Arial', '', 10)
        pdf.cell(0, 6, f'Unit DDP: ${unit_ddp:.2f}', 0, 1, 'L')
        pdf.cell(0, 6, f'Net Margin: {margin_percent:.2f}%', 0, 1, 'L')
    
    pdf.ln(5)
    
    # Cost Breakdown Table
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, 'Cost Breakdown', 0, 1, 'L')
    pdf.set_font('Arial', '', 10)
    pdf.ln(3)
    
    cost_breakdown = analysis_result.get('cost_breakdown', {})
    if cost_breakdown:
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(80, 6, 'Item', 1, 0, 'L')
        pdf.cell(40, 6, 'Amount (USD)', 1, 1, 'R')
        
        pdf.set_font('Arial', '', 10)
        pdf.cell(80, 6, 'Manufacturing', 1, 0, 'L')
        pdf.cell(40, 6, f"${cost_breakdown.get('manufacturing', 0):.2f}", 1, 1, 'R')
        pdf.cell(80, 6, 'Shipping', 1, 0, 'L')
        pdf.cell(40, 6, f"${cost_breakdown.get('shipping', 0):.2f}", 1, 1, 'R')
        pdf.cell(80, 6, 'Duty', 1, 0, 'L')
        pdf.cell(40, 6, f"${cost_breakdown.get('duty', 0):.2f}", 1, 1, 'R')
        
        unit_ddp = (
            float(cost_breakdown.get('manufacturing', 0) or 0) +
            float(cost_breakdown.get('shipping', 0) or 0) +
            float(cost_breakdown.get('duty', 0) or 0) +
            float(cost_breakdown.get('misc', 0) or 0)
        )
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(80, 6, 'Total Unit DDP', 1, 0, 'L')
        pdf.cell(40, 6, f"${unit_ddp:.2f}", 1, 1, 'R')
    
    pdf.ln(5)
    
    # Risk Assessment
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, 'Risk Assessment', 0, 1, 'L')
    pdf.set_font('Arial', '', 10)
    pdf.ln(3)
    
    risk_analysis = analysis_result.get('risk_analysis', {})
    risk_level = risk_analysis.get('level', 'Safe')
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(0, 6, f'Risk Level: {risk_level}', 0, 1, 'L')
    
    risk_notes = risk_analysis.get('notes', [])
    if risk_notes:
        pdf.set_font('Arial', '', 10)
        for note in risk_notes[:5]:  # Limit to first 5 notes
            pdf.cell(0, 6, f'• {note}', 0, 1, 'L')
    
    pdf.ln(5)
    
    # Compliance Warnings
    compliance_warnings = analysis_result.get('compliance_warnings', {})
    risk_warnings_data = analysis_result.get('risk_warnings', {})
    risk_warnings = risk_warnings_data.get('warnings', []) if isinstance(risk_warnings_data, dict) else []
    
    if compliance_warnings or risk_warnings:
        pdf.set_font('Arial', 'B', 14)
        pdf.cell(0, 10, 'Regulatory Warnings', 0, 1, 'L')
        pdf.set_font('Arial', '', 10)
        pdf.ln(3)
        
        # Show risk warnings (handle both dict and string formats)
        for warning in risk_warnings[:5]:  # Limit to first 5
            if isinstance(warning, dict):
                pdf.set_font('Arial', 'B', 10)
                warning_title = str(warning.get('title', warning.get('category', 'Warning')))
                pdf.cell(0, 6, warning_title, 0, 1, 'L')
                pdf.set_font('Arial', '', 9)
                description = str(warning.get('description', warning.get('reason', '')))
                # Split long descriptions
                if len(description) > 100:
                    pdf.multi_cell(0, 5, description[:200] + '...', 0, 'L')
                else:
                    pdf.cell(0, 5, description, 0, 1, 'L')
            elif isinstance(warning, str):
                pdf.set_font('Arial', '', 10)
                pdf.cell(0, 6, f'• {warning}', 0, 1, 'L')
            pdf.ln(2)
    
    pdf.ln(10)
    
    # Footer note
    pdf.set_font('Arial', 'I', 8)
    pdf.cell(0, 5, 'This report is an estimate generated by AI. Actual costs and timelines may vary.', 0, 1, 'C')
    pdf.cell(0, 5, 'Please consult with sourcing professionals for final decisions.', 0, 1, 'C')
    
    # Return PDF as bytes
    # fpdf2's output(dest='S') returns bytes directly - return it as-is
    try:
        pdf_bytes = pdf.output(dest='S')
        # fpdf2 always returns bytes, so just return it directly
        if not isinstance(pdf_bytes, bytes):
            # Safety check: convert to bytes if it's not already
            if isinstance(pdf_bytes, str):
                pdf_bytes = pdf_bytes.encode('utf-8')
            else:
                pdf_bytes = bytes(str(pdf_bytes), 'utf-8')
        return pdf_bytes
    except Exception as e:
        # If output() fails, log and return empty bytes or minimal PDF
        import logging
        logger = logging.getLogger(__name__)
        logger.error(f"PDF output() failed: {e}", exc_info=True)
        # Return minimal error message as bytes
        try:
            error_pdf = PDFReport()
            error_pdf.add_page()
            error_pdf.set_font('Arial', 'B', 12)
            error_pdf.cell(0, 10, 'Error: Could not generate PDF', 0, 1, 'C')
            return error_pdf.output(dest='S')
        except:
            # Last resort: return empty bytes
            return b''


def generate_csv(analysis_result: Dict[str, Any]) -> str:
    """
    Generate CSV export from analysis results.
    
    Args:
        analysis_result: Complete analysis result dictionary
        
    Returns:
        CSV content as string
    """
    import csv
    import io
    
    output = io.StringIO()
    writer = csv.writer(output)
    
    # Header
    writer.writerow(['NexSupply Analysis Report'])
    writer.writerow(['Generated:', datetime.now().strftime("%Y-%m-%d %H:%M:%S")])
    writer.writerow([])
    
    # Executive Summary
    writer.writerow(['Executive Summary'])
    verdict_info = analysis_result.get('verdict', {})
    writer.writerow(['Verdict', verdict_info.get('verdict', 'N/A')])
    
    profitability = analysis_result.get('profitability', {})
    if profitability:
        writer.writerow(['Unit DDP', f"${profitability.get('unit_ddp', 0):.2f}"])
        writer.writerow(['Net Margin %', f"{profitability.get('net_profit_percent', 0):.2f}%"])
    
    writer.writerow([])
    
    # Cost Breakdown
    writer.writerow(['Cost Breakdown'])
    cost_breakdown = analysis_result.get('cost_breakdown', {})
    writer.writerow(['Item', 'Amount (USD)'])
    writer.writerow(['Manufacturing', f"${cost_breakdown.get('manufacturing', 0):.2f}"])
    writer.writerow(['Shipping', f"${cost_breakdown.get('shipping', 0):.2f}"])
    writer.writerow(['Duty', f"${cost_breakdown.get('duty', 0):.2f}"])
    
    unit_ddp = (
        float(cost_breakdown.get('manufacturing', 0) or 0) +
        float(cost_breakdown.get('shipping', 0) or 0) +
        float(cost_breakdown.get('duty', 0) or 0) +
        float(cost_breakdown.get('misc', 0) or 0)
    )
    writer.writerow(['Total Unit DDP', f"${unit_ddp:.2f}"])
    writer.writerow([])
    
    # Assumptions
    assumptions = analysis_result.get('ai_context', {}).get('assumptions', {})
    if assumptions:
        writer.writerow(['Assumptions'])
        writer.writerow(['Volume', assumptions.get('volume', 'N/A')])
        writer.writerow(['Market', assumptions.get('market', 'N/A')])
        writer.writerow(['Channel', assumptions.get('channel', 'N/A')])
        writer.writerow([])
    
    # Risk Assessment
    writer.writerow(['Risk Assessment'])
    risk_analysis = analysis_result.get('risk_analysis', {})
    writer.writerow(['Risk Level', risk_analysis.get('level', 'Safe')])
    
    risk_notes = risk_analysis.get('notes', [])
    if risk_notes:
        writer.writerow(['Risk Notes'])
        for note in risk_notes:
            writer.writerow(['', note])
    
    return output.getvalue()

